# Evaluate the validity of SELFIES generated by transformer models with valency
# constraints modified.
setwd("~/git/invalid-smiles-analysis")
options(stringsAsFactors = FALSE)
library(argparse)

# parse arguments
parser = ArgumentParser(prog = 'outer-parse-valid-SELFIES-transformer.R')
parser$add_argument('--allocation', type = 'character', default = "root")
args = parser$parse_args()

library(tidyverse)
library(magrittr)

# load grid functions
source("R/functions/submit_job.R")
source("R/functions/write_sh.R")
source("R/functions/detect_system.R")

# set up grid
grid = tidyr::crossing(
  database = 'ChEMBL',
  representation = 'SELFIES', 
  enum_factor = 0,
  n_molecules = 1e5,
  min_tc = 0,
  sample_idx = seq_len(10),
  
  # architecture - fixed
  embedding_size = 256,
  n_blocks = 8,
  n_heads = 8,
  max_len = 250,
  dropout = 0,
  exp_factor = 4,
  batch_size = 64,
  learning_rate = 0.0005,
  
  # SELFIES constraints
  constraints = c('none', 'c5'),
  
  ## don't put in filename
  mol_sample_idx = 0,
  max_mols = 10e6
) 

# define input files (*vocab)
input_dir = file.path(base_dir, "training_sets")
input_filenames = pmap_chr(grid, function(...) {
  current = tibble(...)
  current %>%
    dplyr::select(database:sample_idx) %>%
    map2(., names(.), ~ {
      paste0(.y, '=', .x)
    }) %>%
    paste0(collapse = '-') %>%
    paste0('input-', ., '.smi')
})
input_files = file.path(input_dir, input_filenames)
vocab_files = gsub("\\.smi$", ".vocab", input_files)

# define sample files
sample_dir = file.path(base_dir, "sample")
if (!dir.exists(sample_dir))
  dir.create(sample_dir)
sample_dirnames = pmap_chr(grid, function(...) {
  current = tibble(...)
  current %>%
    dplyr::select(database:learning_rate) %>%
    map2(., names(.), ~ {
      paste0(.y, '=', .x)
    }) %>%
    paste0(collapse = '-')
})
sample_files = with(grid, file.path(sample_dir, sample_dirnames,
                                    paste0('sample-', mol_sample_idx, '.csv')))

# define output files (separate for valid vs. invalid)
valid_filenames = with(grid, paste0('sample-', mol_sample_idx, 
                                    '-constraints=', constraints,
                                    '-valid.csv'))
invalid_filenames = with(grid, paste0('sample-', mol_sample_idx, 
                                      '-constraints=', constraints,
                                      '-invalid.csv'))
time_filenames = with(grid, paste0('sample-', mol_sample_idx, 
                                   '-constraints=', constraints,
                                   '-time.csv'))
valid_files = file.path(sample_dir, sample_dirnames, valid_filenames)
invalid_files = file.path(sample_dir, sample_dirnames, invalid_filenames)
time_files = file.path(sample_dir, sample_dirnames, time_filenames)

# now, check for which parameters are already complete
grid0 = grid %>%
  mutate(vocab_file = vocab_files,
         input_file = sample_files,
         valid_file = valid_files,
         invalid_file = invalid_files,
         time_file = time_files) %>% 
  filter(file.exists(input_file)) %>% 
  mutate(nrow = map_int(input_file, ~ system(paste('wc -l', .), 
                                             intern = TRUE) %>% 
                          gsub(" .*$", "", .) %>% 
                          as.integer())) %>% 
  filter(file.exists(vocab_file),
         file.exists(input_file),
         nrow >= 10e6,
         ## time file is the last to be written
         !file.exists(time_file))
# remove columns that are all NA
keep = map_lgl(grid0, ~ any(!is.na(.x) & .x != 'NA'))
grid0 %<>% extract(, keep)

# write the grid that still needs to be run
grid_file = "sh/grids/parse-valid-SELFIES.txt"
grid_dir = dirname(grid_file)
if (!dir.exists(grid_dir))
  dir.create(grid_dir, recursive = TRUE)
write.table(grid0, grid_file, quote = FALSE, row.names = FALSE, sep = "\t")

# write the sh file dynamically
sh_file = 'sh/sample-molecules/parse-valid-SELFIES.sh'
sh_dir = dirname(sh_file)
if (!dir.exists(sh_dir)) 
  dir.create(sh_dir, recursive = TRUE)
write_sh(job_name = 'parse-valid-SELFIES',
         sh_file = sh_file,
         grid_file = grid_file,
         inner_file = 'python/inner-parse-valid-SELFIES.py',
         system = system,
         time = 48,
         mem = 16)

# finally, run the job on whatever system we're on
submit_job(grid0, sh_file, args$allocation, system) 
